#: import COLOUR theme.Colours
#: import ICON theme.Icons
#: import RESOLUTION theme.Size
<Camera>
    FloatLayout:
        Label:
            id: targetLabel


        Image:
            id: imageView
            source: '/home/sander/camera_capture/image_capture.jpg'


        Button:
            text: 'Capture'
            size_hint_max: (120,120)
            pos:(656, 24)
            background_normal: ICON.ADD

            on_press: root.capture()


