#:kivy 1.0
<SetAlarmFor>:
    BoxLayout:
        orientation: 'vertical'

        Label:
            text:'set alarm for'

        Button:
            text: 'cancel'
            on_press:
                root.manager.transition.direction = 'left'
                root.manager.current = 'alarms'

        Button:
            text: 'Confirm'
            on_press:
                root.manager.transition.direction = 'right'
                root.manager.current = 'alarms'