#:kivy 1.0
#:include views/components/background.kv
<WakeUp>:
    Background:
        MDLabel:
            text: 'WAKE UP'

            color: 'black'
            font_style: 'H1'

            halign: 'center'
            pos_hint: {'center_x': 0.5,'center_y': 0.6}

        MDLabel:
            id: CurrentTime

            color: 'black'
            font_style: 'H3'

            halign: 'center'
            pos_hint: {'center_x': 0.5,'center_y': 0.4}

