#:kivy 1.0
#: import COLOUR theme.Colour
#: import ICON theme.Icons
#: import FONTSIZE theme.Text
#: import RESOLUTION theme.Size
#: include views/components/background.kv
#: include views/components/back_button.kv
<WifiSettings>:
    Background:
        Header:
            id: Header

        BackButton:
            on_release:
                root.manager.transition.direction = 'right'
                root.manager.current = 'settings'