#:kivy 1.0
#: import COLOUR theme.Colour
#: import ICON theme.Icons
#: import FONTSIZE theme.Text
#: import RESOLUTION theme.Size
<WifiSettings>:
    BoxLayout:
        orientation: 'vertical'

        Label:
            text:'wifi settings'

        Button:
            text: 'back'
            on_press:
                root.manager.transition.direction = 'right'
                root.manager.current = 'settings'